### ISSUE TITLE
Load components dynamically

### ISSUE THREAD

**Issue by timsim00** [apparatus/fullstack-microservices#2]
Thank you for building this awesome repo. I'm convinced that Seneca + Polymer has a great future.  I'm wondering if you have had any thoughts around the use-case where components are brought down on an as-needed only basis?  For example, if the activity component is loaded into the UI the first time a service action button is clicked?

`<!--<link rel="import" href="/api/activity/component">-->`

`cmp.act({role: 'service1', cmd: 'action1'}, function (err, result) {
      cmp.act({
        role: 'activity', 
        cmd: 'entry', 
        info: {service: 'Service 1', action: 'Action 1'},
        result: result
      });
    });`

The 'activity:entry' message results in the 'no matching pattern' error message.  Is there a way lucius can recognize that a component is missing, fire off the 'activity:component' message first, importHref it, then continue with the 'activity:entry' message?  Or do you see a better way to handle this?

**Comment by davidmarkclements** [comment]
hey @timsim00 there's a loooot of angles here, happy to discuss with you privately

main point is this is just experimental stuff right now, long story short on polymer (or rather future-vanilla), still not quite viable yet since there's _still_ (!!!) no consensus among browser vendors on 
importing components (see https://developer.mozilla.org/en-US/docs/Web/Web_Components/HTML_Imports)

pm me on twitter if you want to talk more, closing for now

**Comment by timsim00** [comment]
Hi David. (unable to pm you on twitter.)  I'm going to try to figure out a way to pull in the component dynamically if it's not already on the page.  Looks like the add('activity:entry') in ready() wires it up.  But in this case it won't be called. In a spa-type of app I'll need a way to add messages before the component is brought down.

**Comment by timsim00** [comment]
@davidmarkclements , I have some ideas around this.  Can you follow me (@drewsimmons00) so I can pm you.  Thanks!
